// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeroWaste.Models;

namespace ZeroWaste.Migrations
{
    [DbContext(typeof(ZeroDbContext))]
    partial class ZeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZeroWaste.Models.Familias", b =>
                {
                    b.Property<int>("IDFamilias")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Morada")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NumeroPessoasAgregado")
                        .IsRequired();

                    b.Property<int>("Rendimento");

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.HasKey("IDFamilias");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("ZeroWaste.Models.Instituicoes", b =>
                {
                    b.Property<int>("IDInstituicoes")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Morada")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NumeroPessoasAbrangidas")
                        .IsRequired();

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.HasKey("IDInstituicoes");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("ZeroWaste.Models.PedidoRestaurante", b =>
                {
                    b.Property<int>("IDPedidoRestaurante")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEntrega");

                    b.Property<bool?>("EstadoEntrega")
                        .IsRequired();

                    b.Property<int>("IDFamilias");

                    b.Property<int>("IDInstituicoes");

                    b.Property<int>("IDRefeicoesRestaurante");

                    b.Property<int>("IDVoluntarios");

                    b.Property<int>("Quantidade");

                    b.HasKey("IDPedidoRestaurante");

                    b.HasIndex("IDFamilias");

                    b.HasIndex("IDInstituicoes");

                    b.HasIndex("IDRefeicoesRestaurante");

                    b.HasIndex("IDVoluntarios");

                    b.ToTable("PedidoRestaurante");
                });

            modelBuilder.Entity("ZeroWaste.Models.PedidoSupermercado", b =>
                {
                    b.Property<int>("IDPedidoSupermercado")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEntrega");

                    b.Property<bool?>("EstadoEntrega")
                        .IsRequired();

                    b.Property<int>("IDFamilias");

                    b.Property<int>("IDInstituicoes");

                    b.Property<int>("IDProdutosSupermercado");

                    b.Property<int>("IDVoluntarios");

                    b.Property<int>("Quantidade");

                    b.HasKey("IDPedidoSupermercado");

                    b.HasIndex("IDFamilias");

                    b.HasIndex("IDInstituicoes");

                    b.HasIndex("IDProdutosSupermercado");

                    b.HasIndex("IDVoluntarios");

                    b.ToTable("PedidoSupermercado");
                });

            modelBuilder.Entity("ZeroWaste.Models.ProdutosSupermercado", b =>
                {
                    b.Property<int>("IDProdutosSupermercado")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDSupermercado");

                    b.Property<int>("IDTipo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Quantidade");

                    b.HasKey("IDProdutosSupermercado");

                    b.HasIndex("IDSupermercado");

                    b.HasIndex("IDTipo");

                    b.ToTable("ProdutosSupermercado");
                });

            modelBuilder.Entity("ZeroWaste.Models.RefeicoesRestaurante", b =>
                {
                    b.Property<int>("IDRefeicoesRestaurante")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDRestaurante");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Quantidade");

                    b.HasKey("IDRefeicoesRestaurante");

                    b.HasIndex("IDRestaurante");

                    b.ToTable("RefeicoesRestaurante");
                });

            modelBuilder.Entity("ZeroWaste.Models.Regras", b =>
                {
                    b.Property<int>("RegrasID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agregado");

                    b.Property<int>("Alimentos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Pedidos");

                    b.Property<int>("Rendimento");

                    b.HasKey("RegrasID");

                    b.ToTable("Regras");
                });

            modelBuilder.Entity("ZeroWaste.Models.Restaurante", b =>
                {
                    b.Property<int>("IDRestaurante")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Morada")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.HasKey("IDRestaurante");

                    b.ToTable("Restaurante");
                });

            modelBuilder.Entity("ZeroWaste.Models.Supermercado", b =>
                {
                    b.Property<int>("IDSupermercado")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Morada")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.HasKey("IDSupermercado");

                    b.ToTable("Supermercado");
                });

            modelBuilder.Entity("ZeroWaste.Models.Tipo", b =>
                {
                    b.Property<int>("IDTipo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("IDTipo");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("ZeroWaste.Models.Voluntarios", b =>
                {
                    b.Property<int>("IDVoluntarios")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNasc");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Morada")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("NrTotalEntregas");

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.HasKey("IDVoluntarios");

                    b.ToTable("Voluntarios");
                });

            modelBuilder.Entity("ZeroWaste.Models.PedidoRestaurante", b =>
                {
                    b.HasOne("ZeroWaste.Models.Familias", "Familias")
                        .WithMany("PedidoRestaurante")
                        .HasForeignKey("IDFamilias")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZeroWaste.Models.Instituicoes", "Instituicoes")
                        .WithMany("PedidoRestaurante")
                        .HasForeignKey("IDInstituicoes")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZeroWaste.Models.RefeicoesRestaurante", "RefeicoesRestaurante")
                        .WithMany("PedidoRestaurante")
                        .HasForeignKey("IDRefeicoesRestaurante")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZeroWaste.Models.Voluntarios", "Voluntarios")
                        .WithMany("PedidoRestaurante")
                        .HasForeignKey("IDVoluntarios")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZeroWaste.Models.PedidoSupermercado", b =>
                {
                    b.HasOne("ZeroWaste.Models.Familias", "Familias")
                        .WithMany("PedidoSupermercado")
                        .HasForeignKey("IDFamilias")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZeroWaste.Models.Instituicoes", "Instituicoes")
                        .WithMany("PedidoSupermercado")
                        .HasForeignKey("IDInstituicoes")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZeroWaste.Models.ProdutosSupermercado", "ProdutosSupermercado")
                        .WithMany("PedidoSupermercado")
                        .HasForeignKey("IDProdutosSupermercado")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZeroWaste.Models.Voluntarios", "Voluntarios")
                        .WithMany("PedidoSupermercado")
                        .HasForeignKey("IDVoluntarios")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZeroWaste.Models.ProdutosSupermercado", b =>
                {
                    b.HasOne("ZeroWaste.Models.Supermercado", "Supermercado")
                        .WithMany("ProdutosSupermercado")
                        .HasForeignKey("IDSupermercado")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZeroWaste.Models.Tipo", "Tipo")
                        .WithMany("ProdutosSupermercado")
                        .HasForeignKey("IDTipo")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZeroWaste.Models.RefeicoesRestaurante", b =>
                {
                    b.HasOne("ZeroWaste.Models.Restaurante", "Restaurante")
                        .WithMany("RefeicoesRestaurante")
                        .HasForeignKey("IDRestaurante")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
